using System.Collections.Generic;

namespace NSW.EliteDangerous.API
{
    public class ShipInfo
    {
        public static IReadOnlyDictionary<ShipModel, string> ShipName { get; } = new Dictionary<ShipModel, string>
        {
            { ShipModel.Adder,               "Adder" },
            { ShipModel.AllianceChallenger,  "Alliance Challenger" },
            { ShipModel.AllianceChieftain,   "Alliance Chieftain" },
            { ShipModel.AllianceCrusader,    "Alliance Crusader" },
            { ShipModel.Anaconda,            "Anaconda" },
            { ShipModel.AspExplorer,         "Asp Explorer"},
            { ShipModel.AspScout,            "Asp Scout"},
            { ShipModel.BelugaLiner,         "Beluga Liner"},
            { ShipModel.CobraMkIII,          "Cobra MkIII"},
            { ShipModel.CobraMkIV,           "Cobra MkIV"},
            { ShipModel.DiamondbackExplorer, "Diamondback Explorer"},
            { ShipModel.DiamondbackScout,    "Diamondback Scout"},
            { ShipModel.Dolphin,             "Dolphin"},
            { ShipModel.Eagle,               "Eagle"},
            { ShipModel.FederalAssaultShip,  "Federal Assault Ship"},
            { ShipModel.FederalCorvette,     "Federal Corvette"},
            { ShipModel.FederalDropship,     "Federal Dropship"},
            { ShipModel.FederalGunship,      "Federal Gunship"},
            { ShipModel.FerDeLance,          "Fer-de-Lance"},
            { ShipModel.Hauler,              "Hauler"},
            { ShipModel.ImperialClipper,     "Imperial Clipper"},
            { ShipModel.ImperialCourier,     "Imperial Courier"},
            { ShipModel.ImperialCutter,      "Imperial Cutter"},
            { ShipModel.ImperialEagle,       "Imperial Eagle"},
            { ShipModel.Keelback,            "Keelback"},
            { ShipModel.KraitMkII,           "Krait MkII"},
            { ShipModel.KraitPhantom,        "Krait Phantom"},
            { ShipModel.Mamba,               "Mamba"},
            { ShipModel.Orca,                "Orca"},
            { ShipModel.Python,              "Python"},
            { ShipModel.Sidewinder,          "Sidewinder"},
            { ShipModel.Type6Transporter,    "Type-6 Transporter"},
            { ShipModel.Type7Transporter,    "Type-7 Transporter"},
            { ShipModel.Type9Heavy,          "Type-9 Heavy"},
            { ShipModel.Type10Defender,      "Type-10 Defender"},
            { ShipModel.ViperMkIII,          "Viper MkIII"},
            { ShipModel.ViperMkIV,           "Viper MkIV"},
            { ShipModel.Vulture,             "Vulture"},
            //NPC
            { ShipModel.PoliceAlliance,      "Allied Police Forces"},
            { ShipModel.PoliceIndependent,   "System Authority Vessel"},
            { ShipModel.PoliceFederation,    "Federal Security Service"},
            { ShipModel.PoliceEmpire,        "Internal Security Service"},
            { ShipModel.MilitaryFederation,  "Federal Navy Ship"},
            { ShipModel.MilitaryIndependent, "System Defence Force"},
            { ShipModel.MilitaryAlliance,    "Alliance Defence Force"},
            { ShipModel.MilitaryEmpire,      "Imperial Navy Vessel"},
            { ShipModel.MilitaryFighterEmpire,      "Imperial Navy Fighter"},
            { ShipModel.MilitaryFighterAlliance,    "Alliance Defence Fighter"},
            { ShipModel.MilitaryFighterIndependent, "System Defence Fighter"},
            { ShipModel.MilitaryFighterFederation,  "Federal Navy Fighter"},
            { ShipModel.AtrIndependent,             "System ATR"},
            { ShipModel.AtrFederation,              "Federal ATR"},
            { ShipModel.AtrEmpire,                  "Imperial ATR"},
            { ShipModel.AtrAlliance,                "Allied ATR"},
            { ShipModel.WeddingBarge,               "Wedding Barge"},
            { ShipModel.SearchAndRescue,            "Search And Rescue Patrol"},
            { ShipModel.IndependentFighter,         "Independent Fighter"},
            { ShipModel.AxMilitaryIndependent,      "System AX Force"},
            { ShipModel.AxMilitaryEmpire,           "Imperial AX Vessel"},
            { ShipModel.AxMilitaryFederation,       "Federal AX Ship"},
            { ShipModel.AxMilitaryAlliance,         "Allied AX Ship"},
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseArmor { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               162 },
            { ShipModel.AllianceChallenger,  540 },
            { ShipModel.AllianceChieftain,   504 },
            { ShipModel.AllianceCrusader,    540 },
            { ShipModel.Anaconda,            525},
            { ShipModel.AspExplorer,         210},
            { ShipModel.AspScout,            324},
            { ShipModel.BelugaLiner,         504},
            { ShipModel.CobraMkIII,          162},
            { ShipModel.CobraMkIV,           216},
            { ShipModel.DiamondbackExplorer, 162},
            { ShipModel.DiamondbackScout,    270},
            { ShipModel.Dolphin,             198},
            { ShipModel.Eagle,               72},
            { ShipModel.FederalAssaultShip,  540},
            { ShipModel.FederalCorvette,     370},
            { ShipModel.FederalDropship,     540},
            { ShipModel.FederalGunship,      630},
            { ShipModel.FerDeLance,          405},
            { ShipModel.Hauler,              90},
            { ShipModel.ImperialClipper,     486},
            { ShipModel.ImperialCourier,     144},
            { ShipModel.ImperialCutter,      720},
            { ShipModel.ImperialEagle,       108},
            { ShipModel.Keelback,            243},
            { ShipModel.KraitMkII,           220},
            { ShipModel.KraitPhantom,        180},
            { ShipModel.Mamba,               230},
            { ShipModel.Orca,                396},
            { ShipModel.Python,              260},
            { ShipModel.Sidewinder,          108},
            { ShipModel.Type6Transporter,    162},
            { ShipModel.Type7Transporter,    306},
            { ShipModel.Type9Heavy,          432},
            { ShipModel.Type10Defender,      1044},
            { ShipModel.ViperMkIII,          126},
            { ShipModel.ViperMkIV,           270},
            { ShipModel.Vulture,             288},
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseSpeed { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               100 },
            { ShipModel.AllianceChallenger,  130 },
            { ShipModel.AllianceChieftain,   150 },
            { ShipModel.AllianceCrusader,    110 },
            { ShipModel.Anaconda,            80},
            { ShipModel.AspExplorer,         120},
            { ShipModel.AspScout,            110},
            { ShipModel.BelugaLiner,         110},
            { ShipModel.CobraMkIII,          140},
            { ShipModel.CobraMkIV,           100},
            { ShipModel.DiamondbackExplorer, 170},
            { ShipModel.DiamondbackScout,    160},
            { ShipModel.Dolphin,             120},
            { ShipModel.Eagle,               180},
            { ShipModel.FederalAssaultShip,  150},
            { ShipModel.FederalCorvette,     100},
            { ShipModel.FederalDropship,     100},
            { ShipModel.FederalGunship,      100},
            { ShipModel.FerDeLance,          220},
            { ShipModel.Hauler,              70},
            { ShipModel.ImperialClipper,     180},
            { ShipModel.ImperialCourier,     220},
            { ShipModel.ImperialCutter,      160},
            { ShipModel.ImperialEagle,       210},
            { ShipModel.Keelback,            90},
            { ShipModel.KraitMkII,           150},
            { ShipModel.KraitPhantom,        160},
            { ShipModel.Mamba,               240},
            { ShipModel.Orca,                200},
            { ShipModel.Python,              140},
            { ShipModel.Sidewinder,          100},
            { ShipModel.Type6Transporter,    90},
            { ShipModel.Type7Transporter,    60},
            { ShipModel.Type9Heavy,          40},
            { ShipModel.Type10Defender,      150},
            { ShipModel.ViperMkIII,          200},
            { ShipModel.ViperMkIV,           175},
            { ShipModel.Vulture,             190},
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseEnergyBoost { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               8 },
            { ShipModel.AllianceChallenger,  19 },
            { ShipModel.AllianceChieftain,   19 },
            { ShipModel.AllianceCrusader,    19 },
            { ShipModel.Anaconda,            27 },
            { ShipModel.AspExplorer,         13 },
            { ShipModel.AspScout,            13 },
            { ShipModel.BelugaLiner,         19 },
            { ShipModel.CobraMkIII,          10 },
            { ShipModel.CobraMkIV,           10 },
            { ShipModel.DiamondbackExplorer, 13 },
            { ShipModel.DiamondbackScout,    10 },
            { ShipModel.Dolphin,             10 },
            { ShipModel.Eagle,               8 },
            { ShipModel.FederalAssaultShip,  19 },
            { ShipModel.FederalCorvette,     27 },
            { ShipModel.FederalDropship,     19 },
            { ShipModel.FederalGunship,      23 },
            { ShipModel.FerDeLance,          19 },
            { ShipModel.Hauler,              7 },
            { ShipModel.ImperialClipper,     19 },
            { ShipModel.ImperialCourier,     10 },
            { ShipModel.ImperialCutter,      23 },
            { ShipModel.ImperialEagle,       8 },
            { ShipModel.Keelback,            10 },
            { ShipModel.KraitMkII,           13 },
            { ShipModel.KraitPhantom,        13 },
            { ShipModel.Mamba,               17 },
            { ShipModel.Orca,                16 },
            { ShipModel.Python,              23 },
            { ShipModel.Sidewinder,          7 },
            { ShipModel.Type6Transporter,    10 },
            { ShipModel.Type7Transporter,    10 },
            { ShipModel.Type9Heavy,          19 },
            { ShipModel.Type10Defender,      19 },
            { ShipModel.ViperMkIII,          10 },
            { ShipModel.ViperMkIV,           10 },
            { ShipModel.Vulture,             16 },
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseSpeedBoost { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               320 },
            { ShipModel.AllianceChallenger,  310 },
            { ShipModel.AllianceChieftain,   330 },
            { ShipModel.AllianceCrusader,    300 },
            { ShipModel.Anaconda,            240 },
            { ShipModel.AspExplorer,         340 },
            { ShipModel.AspScout,            300 },
            { ShipModel.BelugaLiner,         280 },
            { ShipModel.CobraMkIII,          400 },
            { ShipModel.CobraMkIV,           300 },
            { ShipModel.DiamondbackExplorer, 260 },
            { ShipModel.DiamondbackScout,    270 },
            { ShipModel.Dolphin,             350 },
            { ShipModel.Eagle,               350 },
            { ShipModel.FederalAssaultShip,  350 },
            { ShipModel.FederalCorvette,     260 },
            { ShipModel.FederalDropship,     300 },
            { ShipModel.FederalGunship,      280 },
            { ShipModel.FerDeLance,          350 },
            { ShipModel.Hauler,              300 },
            { ShipModel.ImperialClipper,     380 },
            { ShipModel.ImperialCourier,     380 },
            { ShipModel.ImperialCutter,      320 },
            { ShipModel.ImperialEagle,       400 },
            { ShipModel.Keelback,            300 },
            { ShipModel.KraitMkII,           330 },
            { ShipModel.KraitPhantom,        350 },
            { ShipModel.Mamba,               380 },
            { ShipModel.Orca,                380 },
            { ShipModel.Python,              280 },
            { ShipModel.Sidewinder,          320 },
            { ShipModel.Type6Transporter,    350 },
            { ShipModel.Type7Transporter,    300 },
            { ShipModel.Type9Heavy,          200 },
            { ShipModel.Type10Defender,      220 },
            { ShipModel.ViperMkIII,          400 },
            { ShipModel.ViperMkIV,           340 },
            { ShipModel.Vulture,             340 },
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseCargo { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               6 },
            { ShipModel.AllianceChallenger,  40 },
            { ShipModel.AllianceChieftain,   40 },
            { ShipModel.AllianceCrusader,    40 },
            { ShipModel.Anaconda,            114 },
            { ShipModel.AspExplorer,         38 },
            { ShipModel.AspScout,            16 },
            { ShipModel.BelugaLiner,         44 },
            { ShipModel.CobraMkIII,          6 },
            { ShipModel.CobraMkIV,           18 },
            { ShipModel.DiamondbackExplorer, 6 },
            { ShipModel.DiamondbackScout,    12 },
            { ShipModel.Dolphin,             14 },
            { ShipModel.Eagle,               2 },
            { ShipModel.FederalAssaultShip,  32 },
            { ShipModel.FederalCorvette,     76 },
            { ShipModel.FederalDropship,     56 },
            { ShipModel.FederalGunship,      16 },
            { ShipModel.FerDeLance,          24 },
            { ShipModel.Hauler,              8 },
            { ShipModel.ImperialClipper,     74 },
            { ShipModel.ImperialCourier,     12 },
            { ShipModel.ImperialCutter,      164 },
            { ShipModel.ImperialEagle,       2 },
            { ShipModel.Keelback,            42 },
            { ShipModel.KraitMkII,           0 },
            { ShipModel.KraitPhantom,        0 },
            { ShipModel.Mamba,               0 },
            { ShipModel.Orca,                24 },
            { ShipModel.Python,              82 },
            { ShipModel.Sidewinder,          4 },
            { ShipModel.Type6Transporter,    50 },
            { ShipModel.Type7Transporter,    128 },
            { ShipModel.Type9Heavy,          220 },
            { ShipModel.Type10Defender,      220 },
            { ShipModel.ViperMkIII,          4 },
            { ShipModel.ViperMkIV,           18 },
            { ShipModel.Vulture,             8 },
        };

        public static IReadOnlyDictionary<ShipModel, double> BaseFsdRangeLaden { get; } = new Dictionary<ShipModel, double>
        {
            { ShipModel.Adder,               8.47 },
            { ShipModel.AllianceChallenger,  0 },
            { ShipModel.AllianceChieftain,   0 },
            { ShipModel.AllianceCrusader,    7.64 },
            { ShipModel.Anaconda,            8.52 },
            { ShipModel.AspExplorer,         12.07 },
            { ShipModel.AspScout,            10.84 },
            { ShipModel.BelugaLiner,         8.79 },
            { ShipModel.CobraMkIII,          8.47 },
            { ShipModel.CobraMkIV,           9.78 },
            { ShipModel.DiamondbackExplorer, 8.47 },
            { ShipModel.DiamondbackScout,    13.74 },
            { ShipModel.Dolphin,             10.11 },
            { ShipModel.Eagle,               8.27 },
            { ShipModel.FederalAssaultShip,  7.93 },
            { ShipModel.FederalCorvette,     6.03 },
            { ShipModel.FederalDropship,     6.77 },
            { ShipModel.FederalGunship,      6.54 },
            { ShipModel.FerDeLance,          13.53 },
            { ShipModel.Hauler,              8.08 },
            { ShipModel.ImperialClipper,     8.05 },
            { ShipModel.ImperialCourier,     7.69 },
            { ShipModel.ImperialCutter,      7.57 },
            { ShipModel.ImperialEagle,       8.03 },
            { ShipModel.Keelback,            9.34 },
            { ShipModel.KraitMkII,           0 },
            { ShipModel.KraitPhantom,        0 },
            { ShipModel.Mamba,               0 },
            { ShipModel.Orca,                6.66 },
            { ShipModel.Python,              7.36 },
            { ShipModel.Sidewinder,          6.96 },
            { ShipModel.Type6Transporter,    10.07 },
            { ShipModel.Type7Transporter,    8.63 },
            { ShipModel.Type9Heavy,          6.62 },
            { ShipModel.Type10Defender,      5.87 },
            { ShipModel.ViperMkIII,          6.66 },
            { ShipModel.ViperMkIV,           9.69 },
            { ShipModel.Vulture,             7.75 },
        };

        public static IReadOnlyDictionary<ShipModel, double> BaseFsdRangeUnladen { get; } = new Dictionary<ShipModel, double>
        {
            { ShipModel.Adder,               9.12 },
            { ShipModel.AllianceChallenger,  8.58 },
            { ShipModel.AllianceChieftain,   9.59 },
            { ShipModel.AllianceCrusader,    8.21 },
            { ShipModel.Anaconda,            9.41 },
            { ShipModel.AspExplorer,         13.12 },
            { ShipModel.AspScout,            11.59 },
            { ShipModel.BelugaLiner,         9.01 },
            { ShipModel.CobraMkIII,          9.12 },
            { ShipModel.CobraMkIV,           10.46 },
            { ShipModel.DiamondbackExplorer, 9.12 },
            { ShipModel.DiamondbackScout,    14.15 },
            { ShipModel.Dolphin,             10.67 },
            { ShipModel.Eagle,               8.47 },
            { ShipModel.FederalAssaultShip,  8.30 },
            { ShipModel.FederalCorvette,     6.31 },
            { ShipModel.FederalDropship,     7.25 },
            { ShipModel.FederalGunship,      6.66 },
            { ShipModel.FerDeLance,          14.33 },
            { ShipModel.Hauler,              9.87 },
            { ShipModel.ImperialClipper,     8.98 },
            { ShipModel.ImperialCourier,     8.83 },
            { ShipModel.ImperialCutter,      8.21 },
            { ShipModel.ImperialEagle,       8.22 },
            { ShipModel.Keelback,            10.94 },
            { ShipModel.KraitMkII,           0 },
            { ShipModel.KraitPhantom,        0 },
            { ShipModel.Mamba,               0 },
            { ShipModel.Orca,                6.86 },
            { ShipModel.Python,              8.23 },
            { ShipModel.Sidewinder,          7.56 },
            { ShipModel.Type6Transporter,    12.39 },
            { ShipModel.Type7Transporter,    10.68 },
            { ShipModel.Type9Heavy,          7.71 },
            { ShipModel.Type10Defender,      6.97 },
            { ShipModel.ViperMkIII,          6.92 },
            { ShipModel.ViperMkIV,           10.36 },
            { ShipModel.Vulture,             7.93 },
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseHullMass { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               35 },
            { ShipModel.AllianceChallenger,  450 },
            { ShipModel.AllianceChieftain,   400 },
            { ShipModel.AllianceCrusader,    500 },
            { ShipModel.Anaconda,            400 },
            { ShipModel.AspExplorer,         280 },
            { ShipModel.AspScout,            150 },
            { ShipModel.BelugaLiner,         950 },
            { ShipModel.CobraMkIII,          180 },
            { ShipModel.CobraMkIV,           210 },
            { ShipModel.DiamondbackExplorer, 260 },
            { ShipModel.DiamondbackScout,    298 },
            { ShipModel.Dolphin,             140 },
            { ShipModel.Eagle,               50 },
            { ShipModel.FederalAssaultShip,  480 },
            { ShipModel.FederalCorvette,     900 },
            { ShipModel.FederalDropship,     580 },
            { ShipModel.FederalGunship,      580 },
            { ShipModel.FerDeLance,          250 },
            { ShipModel.Hauler,              14 },
            { ShipModel.ImperialClipper,     400 },
            { ShipModel.ImperialCourier,     35 },
            { ShipModel.ImperialCutter,      1100 },
            { ShipModel.ImperialEagle,       50 },
            { ShipModel.Keelback,            180 },
            { ShipModel.KraitMkII,           320 },
            { ShipModel.KraitPhantom,        270 },
            { ShipModel.Mamba,               250 },
            { ShipModel.Orca,                580 },
            { ShipModel.Python,              350 },
            { ShipModel.Sidewinder,          25 },
            { ShipModel.Type6Transporter,    155 },
            { ShipModel.Type7Transporter,    420 },
            { ShipModel.Type9Heavy,          1000 },
            { ShipModel.Type10Defender,      1200 },
            { ShipModel.ViperMkIII,          60 },
            { ShipModel.ViperMkIV,           190 },
            { ShipModel.Vulture,             230 },
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseManoeuvrability { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               4 },
            { ShipModel.AllianceChallenger,  4 },
            { ShipModel.AllianceChieftain,   4 },
            { ShipModel.AllianceCrusader,    3 },
            { ShipModel.Anaconda,            1 },
            { ShipModel.AspExplorer,         4 },
            { ShipModel.AspScout,            5 },
            { ShipModel.BelugaLiner,         2 },
            { ShipModel.CobraMkIII,          4 },
            { ShipModel.CobraMkIV,           5 },
            { ShipModel.DiamondbackExplorer, 4 },
            { ShipModel.DiamondbackScout,    4 },
            { ShipModel.Dolphin,             3 },
            { ShipModel.Eagle,               7 },
            { ShipModel.FederalAssaultShip,  4 },
            { ShipModel.FederalCorvette,     2 },
            { ShipModel.FederalDropship,     3 },
            { ShipModel.FederalGunship,      1 },
            { ShipModel.FerDeLance,          4 },
            { ShipModel.Hauler,              4 },
            { ShipModel.ImperialClipper,     5 },
            { ShipModel.ImperialCourier,     4 },
            { ShipModel.ImperialCutter,      0 },
            { ShipModel.ImperialEagle,       5 },
            { ShipModel.Keelback,            2 },
            { ShipModel.KraitMkII,           0 },
            { ShipModel.KraitPhantom,        0 },
            { ShipModel.Mamba,               0 },
            { ShipModel.Orca,                1 },
            { ShipModel.Python,              2 },
            { ShipModel.Sidewinder,          5 },
            { ShipModel.Type6Transporter,    3 },
            { ShipModel.Type7Transporter,    1 },
            { ShipModel.Type9Heavy,          0 },
            { ShipModel.Type10Defender,      0 },
            { ShipModel.ViperMkIII,          4 },
            { ShipModel.ViperMkIV,           3 },
            { ShipModel.Vulture,             5 },
        };

        public static IReadOnlyDictionary<ShipModel, int> BasePrice { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               87808 },
            { ShipModel.AllianceChallenger,  30472252 },
            { ShipModel.AllianceChieftain,   19382250 },
            { ShipModel.AllianceCrusader,    25367279 },
            { ShipModel.Anaconda,            146969451 },
            { ShipModel.AspExplorer,         6661153 },
            { ShipModel.AspScout,            3862130 },
            { ShipModel.BelugaLiner,         84532780 },
            { ShipModel.CobraMkIII,          379718 },
            { ShipModel.CobraMkIV,           745610 },
            { ShipModel.DiamondbackExplorer, 1894760 },
            { ShipModel.DiamondbackScout,    564330 },
            { ShipModel.Dolphin,             1337330 },
            { ShipModel.Eagle,               44800 },
            { ShipModel.FederalAssaultShip,  19814205 },
            { ShipModel.FederalCorvette,     180327022 },
            { ShipModel.FederalDropship,     14314210 },
            { ShipModel.FederalGunship,      35814210 },
            { ShipModel.FerDeLance,          51567040 },
            { ShipModel.Hauler,              52720 },
            { ShipModel.ImperialClipper,     22295860 },
            { ShipModel.ImperialCourier,     2542931 },
            { ShipModel.ImperialCutter,      203745220 },
            { ShipModel.ImperialEagle,       110830 },
            { ShipModel.Keelback,            3048000 },
            { ShipModel.KraitMkII,           45814205 },
            { ShipModel.KraitPhantom,        48539887 },
            { ShipModel.Mamba,               0 },
            { ShipModel.Orca,                48539887 },
            { ShipModel.Python,              56978179 },
            { ShipModel.Sidewinder,          32000 },
            { ShipModel.Type6Transporter,    1045945 },
            { ShipModel.Type7Transporter,    17472252 },
            { ShipModel.Type9Heavy,          76555842 },
            { ShipModel.Type10Defender,      124755342 },
            { ShipModel.ViperMkIII,          142931 },
            { ShipModel.ViperMkIV,           426990 },
            { ShipModel.Vulture,             4925615 },
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseShield { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               78 },
            { ShipModel.AllianceChallenger,  208 },
            { ShipModel.AllianceChieftain,   162 },
            { ShipModel.AllianceCrusader,    126 },
            { ShipModel.Anaconda,            362 },
            { ShipModel.AspExplorer,         152 },
            { ShipModel.AspScout,            105 },
            { ShipModel.BelugaLiner,         92 },
            { ShipModel.CobraMkIII,          78 },
            { ShipModel.CobraMkIV,           92 },
            { ShipModel.DiamondbackExplorer, 78 },
            { ShipModel.DiamondbackScout,    115 },
            { ShipModel.Dolphin,             143 },
            { ShipModel.Eagle,               78 },
            { ShipModel.FederalAssaultShip,  133 },
            { ShipModel.FederalCorvette,     516 },
            { ShipModel.FederalDropship,     104 },
            { ShipModel.FederalGunship,      186 },
            { ShipModel.FerDeLance,          271 },
            { ShipModel.Hauler,              65 },
            { ShipModel.ImperialClipper,     186 },
            { ShipModel.ImperialCourier,     230 },
            { ShipModel.ImperialCutter,      703 },
            { ShipModel.ImperialEagle,       104 },
            { ShipModel.Keelback,            99 },
            { ShipModel.KraitMkII,           220 },
            { ShipModel.KraitPhantom,        200 },
            { ShipModel.Mamba,               270 },
            { ShipModel.Orca,                114 },
            { ShipModel.Python,              294 },
            { ShipModel.Sidewinder,          52 },
            { ShipModel.Type6Transporter,    77 },
            { ShipModel.Type7Transporter,    78 },
            { ShipModel.Type9Heavy,          88 },
            { ShipModel.Type10Defender,      99 },
            { ShipModel.ViperMkIII,          137 },
            { ShipModel.ViperMkIV,           103 },
            { ShipModel.Vulture,             293 },
        };

        public static IReadOnlyDictionary<ShipModel, int> BaseMaxSpeed { get; } = new Dictionary<ShipModel, int>
        {
            { ShipModel.Adder,               220 },
            { ShipModel.AllianceChallenger,  200 },
            { ShipModel.AllianceChieftain,   230 },
            { ShipModel.AllianceCrusader,    180 },
            { ShipModel.Anaconda,            180 },
            { ShipModel.AspExplorer,         250 },
            { ShipModel.AspScout,            220 },
            { ShipModel.BelugaLiner,         200 },
            { ShipModel.CobraMkIII,          280 },
            { ShipModel.CobraMkIV,           200 },
            { ShipModel.DiamondbackExplorer, 280 },
            { ShipModel.DiamondbackScout,    260 },
            { ShipModel.Dolphin,             250 },
            { ShipModel.Eagle,               240 },
            { ShipModel.FederalAssaultShip,  210 },
            { ShipModel.FederalCorvette,     200 },
            { ShipModel.FederalDropship,     180 },
            { ShipModel.FederalGunship,      170 },
            { ShipModel.FerDeLance,          260 },
            { ShipModel.Hauler,              200 },
            { ShipModel.ImperialClipper,     300 },
            { ShipModel.ImperialCourier,     280 },
            { ShipModel.ImperialCutter,      200 },
            { ShipModel.ImperialEagle,       300 },
            { ShipModel.Keelback,            200 },
            { ShipModel.KraitMkII,           240 },
            { ShipModel.KraitPhantom,        250 },
            { ShipModel.Mamba,               310 },
            { ShipModel.Orca,                300 },
            { ShipModel.Python,              230 },
            { ShipModel.Sidewinder,          220 },
            { ShipModel.Type6Transporter,    220 },
            { ShipModel.Type7Transporter,    180 },
            { ShipModel.Type9Heavy,          130 },
            { ShipModel.Type10Defender,      180 },
            { ShipModel.ViperMkIII,          320 },
            { ShipModel.ViperMkIV,           270 },
            { ShipModel.Vulture,             210 },
        };

        public ShipModel Model { get; }
        public string Name => ShipName.TryGetValue(Model, out string value) ? value : string.Empty;
        public int Speed => BaseSpeed.TryGetValue(Model, out int value) ? value : 0;
        public int MaxSpeed => BaseMaxSpeed.TryGetValue(Model, out int value) ? value : 0;
        public int SpeedBoost => BaseSpeedBoost.TryGetValue(Model, out int value) ? value : 0;
        public int EnergyBoost => BaseEnergyBoost.TryGetValue(Model, out int value) ? value : 0;
        public int Cargo => BaseCargo.TryGetValue(Model, out int value) ? value : 0;
        public double FsdRangeLaden => BaseFsdRangeLaden.TryGetValue(Model, out double value) ? value : 0;
        public double FsdRangeUnladen => BaseFsdRangeUnladen.TryGetValue(Model, out double value) ? value : 0;
        public int HullMass => BaseHullMass.TryGetValue(Model, out int value) ? value : 0;
        public int Shield => BaseShield.TryGetValue(Model, out int value) ? value : 0;
        public int Manoeuvrability => BaseManoeuvrability.TryGetValue(Model, out int value) ? value : 0;
        public int Price => BasePrice.TryGetValue(Model, out int value) ? value : 0;

        internal ShipInfo(ShipModel model)
        {
            Model = model;
        }
    }
}