using System.ComponentModel;

namespace NSW.EliteDangerous.API
{
    public enum ShipModel
    {
        Unknown,
        Adder,
        AllianceChallenger,
        AllianceChieftain,
        AllianceCrusader,
        Anaconda,
        AspExplorer,
        AspScout,
        BelugaLiner,
        CobraMkIII,
        CobraMkIV,
        DiamondbackExplorer,
        DiamondbackScout,
        Dolphin,
        Eagle,
        FederalAssaultShip,
        FederalCorvette,
        FederalDropship,
        FederalGunship,
        FerDeLance,
        Hauler,
        ImperialClipper,
        ImperialCourier,
        ImperialCutter,
        ImperialEagle,
        Keelback,
        KraitMkII,
        KraitPhantom,
        Mamba,
        Orca,
        Python,
        Sidewinder,
        Type6Transporter,
        Type7Transporter,
        Type9Heavy,
        Type10Defender,
        ViperMkIII,
        ViperMkIV,
        Vulture,
        // NPC
        Npc,
        WeddingBarge,
        SearchAndRescue,
        IndependentFighter,

        PoliceAlliance,
        PoliceIndependent,
        PoliceFederation,
        PoliceEmpire,

        MilitaryFederation,
        MilitaryIndependent,
        MilitaryAlliance,
        MilitaryEmpire,

        MilitaryFighterEmpire,
        MilitaryFighterAlliance,
        MilitaryFighterIndependent,
        MilitaryFighterFederation,

        AtrIndependent,
        AtrFederation,
        AtrEmpire,
        AtrAlliance,

        AxMilitaryIndependent,
        AxMilitaryEmpire,
        AxMilitaryFederation,
        AxMilitaryAlliance,
    }
}