namespace NSW.EliteDangerous.API
{
    public enum State
    {
        None,
        Boom,
        Bust,
        CivilUnrest,
        CivilWar,
        Election,
        Expansion,
        Famine,
        Investment,
        Lockdown,
        Outbreak,
        Retreat,
        War,
        CivilLiberty,
        PirateAttack,
        Drought,
        Colonisation,
        Revolution,
        ColdWar,
        TechnologicalLeap,
        TradeWar,
        Terrorism,
        HistoricEvent,
        InfrastructureFailure,
        PublicHoliday,
        NaturalDisaster,
        Blight
    }
}